spring:
  application:
    name: OptionAtlas API

  datasource:
    url: jdbc:postgresql://localhost:5432/optionatlas
    username: optionatlas
    password: optionatlas

  jpa:
    hibernate:
      ddl-auto: none # manage schema with flyway later
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

jwt:
  issuer: optionatlas
  accessTtlSeconds: 3600 # 1 hour
  secret: 'this-is-a-long-random-secret-string-at-least-32-bytes'
